import {Empleado, Contrato, Movimiento} from '../types';

// ────────────────────────────────────────────────────────
//  Mock data – Personal
// ────────────────────────────────────────────────────────

export const empleadosMock: Empleado[] = [
  {
    id: '1',
    nombre: 'Carlos',
    apellido: 'Rodríguez',
    cargo: 'Gerente de Proyectos',
    departamento: 'Tecnología',
    fechaIngreso: '2020-03-15',
    estado: 'activo',
    email: 'carlos.rodriguez@empresa.com',
    telefono: '+57 310 123 4567',
    salario: 5800000,
  },
  {
    id: '2',
    nombre: 'Sofía',
    apellido: 'Martínez',
    cargo: 'Desarrolladora Senior',
    departamento: 'Tecnología',
    fechaIngreso: '2021-06-01',
    estado: 'activo',
    email: 'sofia.martinez@empresa.com',
    telefono: '+57 311 234 5678',
    salario: 4500000,
  },
  {
    id: '3',
    nombre: 'Andrés',
    apellido: 'López',
    cargo: 'Analista Financiero',
    departamento: 'Finanzas',
    fechaIngreso: '2019-11-20',
    estado: 'activo',
    email: 'andres.lopez@empresa.com',
    telefono: '+57 312 345 6789',
    salario: 3900000,
  },
  {
    id: '4',
    nombre: 'Valentina',
    apellido: 'García',
    cargo: 'Diseñadora UX',
    departamento: 'Diseño',
    fechaIngreso: '2022-01-10',
    estado: 'activo',
    email: 'valentina.garcia@empresa.com',
    telefono: '+57 313 456 7890',
    salario: 3200000,
  },
  {
    id: '5',
    nombre: 'Miguel',
    apellido: 'Torres',
    cargo: 'Supervisor Operativo',
    departamento: 'Operaciones',
    fechaIngreso: '2018-07-05',
    estado: 'licencia',
    email: 'miguel.torres@empresa.com',
    telefono: '+57 314 567 8901',
    salario: 3600000,
  },
  {
    id: '6',
    nombre: 'Laura',
    apellido: 'Hernández',
    cargo: 'Recursos Humanos',
    departamento: 'RRHH',
    fechaIngreso: '2023-03-01',
    estado: 'activo',
    email: 'laura.hernandez@empresa.com',
    telefono: '+57 315 678 9012',
    salario: 2800000,
  },
  {
    id: '7',
    nombre: 'Javier',
    apellido: 'Sánchez',
    cargo: 'Contador',
    departamento: 'Finanzas',
    fechaIngreso: '2017-09-15',
    estado: 'inactivo',
    email: 'javier.sanchez@empresa.com',
    telefono: '+57 316 789 0123',
    salario: 0,
  },
];

// ────────────────────────────────────────────────────────
//  Mock data – Contratos
// ────────────────────────────────────────────────────────

export const contratosMock: Contrato[] = [
  {
    id: 'C001',
    empleadoId: '1',
    empleadoNombre: 'Carlos Rodríguez',
    tipo: 'indefinido',
    fechaInicio: '2020-03-15',
    salario: 5800000,
    estado: 'activo',
    observaciones: 'Contrato indefinido gerencia de proyectos',
  },
  {
    id: 'C002',
    empleadoId: '2',
    empleadoNombre: 'Sofía Martínez',
    tipo: 'indefinido',
    fechaInicio: '2021-06-01',
    salario: 4500000,
    estado: 'activo',
  },
  {
    id: 'C003',
    empleadoId: '3',
    empleadoNombre: 'Andrés López',
    tipo: 'indefinido',
    fechaInicio: '2019-11-20',
    salario: 3900000,
    estado: 'activo',
  },
  {
    id: 'C004',
    empleadoId: '4',
    empleadoNombre: 'Valentina García',
    tipo: 'temporal',
    fechaInicio: '2022-01-10',
    fechaFin: '2024-01-10',
    salario: 3200000,
    estado: 'vencido',
    observaciones: 'Contrato temporal renovable',
  },
  {
    id: 'C005',
    empleadoId: '4',
    empleadoNombre: 'Valentina García',
    tipo: 'indefinido',
    fechaInicio: '2024-01-11',
    salario: 3500000,
    estado: 'activo',
    observaciones: 'Renovación a contrato indefinido',
  },
  {
    id: 'C006',
    empleadoId: '5',
    empleadoNombre: 'Miguel Torres',
    tipo: 'indefinido',
    fechaInicio: '2018-07-05',
    salario: 3600000,
    estado: 'activo',
    observaciones: 'En licencia médica',
  },
  {
    id: 'C007',
    empleadoId: '6',
    empleadoNombre: 'Laura Hernández',
    tipo: 'practicas',
    fechaInicio: '2023-03-01',
    fechaFin: '2023-09-01',
    salario: 2000000,
    estado: 'vencido',
  },
  {
    id: 'C008',
    empleadoId: '6',
    empleadoNombre: 'Laura Hernández',
    tipo: 'indefinido',
    fechaInicio: '2023-09-02',
    salario: 2800000,
    estado: 'activo',
    observaciones: 'Vinculación directa post-prácticas',
  },
  {
    id: 'C009',
    empleadoId: '7',
    empleadoNombre: 'Javier Sánchez',
    tipo: 'indefinido',
    fechaInicio: '2017-09-15',
    fechaFin: '2024-12-31',
    salario: 3400000,
    estado: 'rescindido',
    observaciones: 'Renuncia voluntaria',
  },
];

// ────────────────────────────────────────────────────────
//  Mock data – Movimientos
// ────────────────────────────────────────────────────────

export const movimientosMock: Movimiento[] = [
  {
    id: 'M001',
    empleadoId: '1',
    empleadoNombre: 'Carlos Rodríguez',
    tipo: 'ingreso',
    concepto: 'Salario Mayo 2025',
    monto: 5800000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M002',
    empleadoId: '2',
    empleadoNombre: 'Sofía Martínez',
    tipo: 'ingreso',
    concepto: 'Salario Mayo 2025',
    monto: 4500000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M003',
    empleadoId: '3',
    empleadoNombre: 'Andrés López',
    tipo: 'ingreso',
    concepto: 'Salario Mayo 2025',
    monto: 3900000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M004',
    empleadoId: '1',
    empleadoNombre: 'Carlos Rodríguez',
    tipo: 'descuento',
    concepto: 'Descuento salud (4%)',
    monto: 232000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M005',
    empleadoId: '2',
    empleadoNombre: 'Sofía Martínez',
    tipo: 'descuento',
    concepto: 'Descuento pensión (4%)',
    monto: 180000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M006',
    empleadoId: '4',
    empleadoNombre: 'Valentina García',
    tipo: 'ingreso',
    concepto: 'Salario Mayo 2025',
    monto: 3500000,
    fecha: '2025-05-01',
    estado: 'procesado',
  },
  {
    id: 'M007',
    empleadoId: '3',
    empleadoNombre: 'Andrés López',
    tipo: 'egreso',
    concepto: 'Anticipo de nómina',
    monto: 500000,
    fecha: '2025-04-20',
    estado: 'procesado',
  },
  {
    id: 'M008',
    empleadoId: '6',
    empleadoNombre: 'Laura Hernández',
    tipo: 'ingreso',
    concepto: 'Salario Mayo 2025',
    monto: 2800000,
    fecha: '2025-05-01',
    estado: 'pendiente',
  },
  {
    id: 'M009',
    empleadoId: '5',
    empleadoNombre: 'Miguel Torres',
    tipo: 'ingreso',
    concepto: 'Auxilio Licencia Médica',
    monto: 1800000,
    fecha: '2025-05-01',
    estado: 'pendiente',
  },
  {
    id: 'M010',
    empleadoId: '2',
    empleadoNombre: 'Sofía Martínez',
    tipo: 'ingreso',
    concepto: 'Bonificación Proyecto Alpha',
    monto: 600000,
    fecha: '2025-04-30',
    estado: 'procesado',
  },
];
